# Generated by Django 3.2.25 on 2024-08-08 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devotions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devotions',
            old_name='description',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='devotions',
            name='title',
        ),
    ]
