# Generated by Django 3.2.25 on 2024-08-04 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronounce', models.CharField(choices=[('0', 'She/Her'), ('1', 'They/Them'), ('2', 'He/Him'), ('3', 'Other')], default='1', max_length=20)),
                ('devotion', models.CharField(choices=[('0', 'Content'), ('1', 'Anxious'), ('2', 'Brave'), ('3', 'Lonely')], default='0', max_length=20)),
                ('message', models.TextField(blank=True, default='', null=True)),
                ('schedule_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Devotions',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devotion', models.CharField(choices=[('0', 'Content'), ('1', 'Anxious'), ('2', 'Brave'), ('3', 'Lonely')], max_length=20)),
                ('pronouns', models.CharField(choices=[('0', 'She/Her'), ('1', 'They/Them'), ('2', 'He/Him'), ('3', 'Other')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserDevotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('devotion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.devotion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Devotions',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Devices',
                'ordering': ('created_at',),
            },
        ),
    ]
