# Generated by Django 3.2.25 on 2024-08-04 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_devotion_userdevices_userdevotion_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'managed': True, 'verbose_name_plural': 'User Profiles'},
        ),
    ]
