# Generated by Django 3.2.25 on 2024-08-04 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_userprofile_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devotion',
            old_name='pronounce',
            new_name='pronoun',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='pronouns',
            new_name='pronoun',
        ),
    ]
