# Generated by Django 3.2.25 on 2024-08-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20240804_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='devotion',
            field=models.CharField(choices=[('0', 'Content'), ('1', 'Anxious'), ('2', 'Brave'), ('3', 'Lonely')], max_length=20, null=True),
        ),
    ]
