# Generated by Django 3.2.25 on 2024-08-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_userprofile_devotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotion',
            name='devotion',
            field=models.BigIntegerField(choices=[(0, 'Content'), (1, 'Anxious'), (2, 'Brave'), (3, 'Lonely')], default='0'),
        ),
        migrations.AlterField(
            model_name='devotion',
            name='pronoun',
            field=models.BigIntegerField(choices=[(0, 'She/Her'), (1, 'They/Them'), (2, 'He/Him'), (3, 'Other')], default='1'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='devotion',
            field=models.BigIntegerField(choices=[(0, 'Content'), (1, 'Anxious'), (2, 'Brave'), (3, 'Lonely')], null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pronoun',
            field=models.BigIntegerField(choices=[(0, 'She/Her'), (1, 'They/Them'), (2, 'He/Him'), (3, 'Other')]),
        ),
    ]
