# Generated by Django 3.2.25 on 2024-08-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevotion',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
