# Generated by Django 3.2.25 on 2024-08-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_userdevotion_is_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdevotion',
            options={'verbose_name_plural': 'User Devotions'},
        ),
        migrations.RemoveField(
            model_name='userdevotion',
            name='created_at',
        ),
    ]
