# Generated by Django 3.2.25 on 2024-08-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_pin_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pin_hash',
        ),
    ]
