# Generated by Django 3.2.25 on 2024-08-08 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_pin_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronoun', models.IntegerField(choices=[(0, 'She/Her'), (1, 'They/Them'), (2, 'He/Him'), (3, 'Other')])),
                ('devotion', models.IntegerField(choices=[(0, 'Content'), (1, 'Anxious'), (2, 'Brave'), (3, 'Lonely')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
