# Generated by Django 3.2.25 on 2024-08-04 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_userprofile_user'),
        ('users', '0004_remove_user_pin_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='home.userprofile'),
        ),
    ]
