# Generated by Django 3.2.25 on 2024-08-04 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_profile',
        ),
    ]
